### ISSUE TITLE
"No Internet access"

### ISSUE THREAD

**Issue by Watcher-Guru3D** [Wagnard/display-drivers-uninstaller#55]
From Guru3D forum

https://forums.guru3d.com/threads/display-driver-uninstaller-thread.379506/page-95#post-5819321

I've been using DDU for years without any issues. A few moments ago, I used it once more (latest version) before installing the latest Nvidia drivers (452.06).

Everything went smoothly... except for the fact that Windows now thinks there's no internet connection, even though I'm typing this message from the same PC hardwired to my router via Ethernet.

Under Settings, the network status is listed as "No Internet access". I can't login and download anything from the Microsoft Store and Xbox apps, as I'm hit with a "You'll need the Internet for this" error message (even though I can navigate the store just fine). If I connect via WiFi, the same behavior happens. I've tried everything: clearing the Store's cache, setting up a static IP address, disabling and re-enabling the network adapter, flushing DNS and resetting IP via IP config on a command prompt window and even following the troubleshooter and going with a full network reset. Nothing helped.

Not sure if this has anything to do with DDU or not. I always unplug the Ethernet cable before running the software and rebooting to safe mode. I also always check the option to prevent Windows from installing updates until the new driver is completely installed. The only difference is that this time I forgot to uncheck that setting after completing the installation. I plugged the Ethernet cable back in and used my PC for a while before realizing I had left the setting checked/enabled. I usually uncheck/disable it before even reconnecting to the internet (by plugging the Ethernet cable back in). As soon as I noted the issue with Windows apps, I opened DDU, unchecked/disabled the setting and restarted my PC, but the issue persists.

Any ideas?

**Comment by Wagnard** [comment]
Hey, @Wagnard, thanks for offering to help me.

As it turns out, it really didn't have anything to do with DDU. I was able to solve my problem (for now, at least) by editing a registry key... that I had never touched before.

Found the answer thanks to this thread, where someone else reported having the same issue and was able to fix it by editing the registry key "Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet" and setting the DWORD value of "EnableActiveProbing" to 1 (default appears to be 0).

Weird thing is that I had never edited that key before, nor did I have any issues with Windows not being able to detect internet access for its own apps and settings prior to last week.

I did update to 2004 sometime before the latest drivers, so, that may be related to the problem. Microsoft always work in mysterious ways.

P.S.: Also, thanks @Watcher for pinging Wagnard. :)
